name: Deploy Python App to GCP

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      # Deploy to GCP (e.g., Cloud Run)
      - name: Deploy to Cloud Run
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud run deploy YOUR_SERVICE_NAME \
            --image gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME \
            --platform managed \
            --region YOUR_REGION \
            --allow-unauthenticated
