name: Terraform Build, Test, and Deploy to GCP

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the job

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 3: Authenticate with GCP using the service account
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 4: Set up Google Cloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      # Step 5: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan -var="gcp_cred=${{ secrets.GCP_CREDENTIALS }}"

      # Step 7: Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan -var="gcp_cred=${{ secrets.GCP_CREDENTIALS }}"
#        env:
#          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
